CREATE TABLE "career_openings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"opening_type" text DEFAULT 'job' NOT NULL,
	"department" text NOT NULL,
	"employment_type" text DEFAULT 'full-time' NOT NULL,
	"location" text NOT NULL,
	"work_mode" text DEFAULT 'hybrid' NOT NULL,
	"short_description" text NOT NULL,
	"about_role" text NOT NULL,
	"responsibilities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"requirements" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"nice_to_have" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"skills" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"experience" text NOT NULL,
	"salary" jsonb,
	"internship" jsonb,
	"status" text DEFAULT 'draft' NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone,
	"closing_date" timestamp with time zone,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "career_openings_slug_unique" UNIQUE("slug")
);
