import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { interns } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import {
  normalizeInternshipId,
  isValidInternshipId,
  calculateInternshipProgress,
} from "@/lib/internship-utils";
import { getCertificateSerialNumber } from "@/lib/certificate-generator";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const rawId = searchParams.get("id");

    if (!rawId || !rawId.trim()) {
      return NextResponse.json(
        { error: "Please enter an Internship ID." },
        { status: 400 }
      );
    }

    const normalizedId = normalizeInternshipId(rawId);

    if (!isValidInternshipId(normalizedId)) {
      return NextResponse.json(
        { error: "Please enter a valid Internship ID, for example XSW-INTERN-001." },
        { status: 400 }
      );
    }

    // Query published intern record
    const [intern] = await db
      .select()
      .from(interns)
      .where(and(eq(interns.internshipId, normalizedId), eq(interns.isPublished, true)));

    if (!intern) {
      return NextResponse.json(
        { error: "Internship record not found. Please check your Internship ID and try again." },
        { status: 404 }
      );
    }

    // Dynamic timeline & progress calculation
    const progress = calculateInternshipProgress(intern.startDate, intern.endDate, intern.status);

    // Certificate eligibility check:
    // Only completed internships that are NOT terminated can view/download certificate
    const canAccessCertificate = progress.isCompleted && intern.status !== "TERMINATED";

    return NextResponse.json({
      success: true,
      intern: {
        internshipId: intern.internshipId,
        fullName: intern.fullName,
        profileImage: intern.profileImage,
        role: intern.role,
        department: intern.department,
        internshipType: intern.internshipType,
        startDate: intern.startDate,
        endDate: intern.endDate,
        duration: intern.duration,
        status: intern.status,
        skills: intern.skills || [],
        description: intern.description,
        performanceSummary: intern.performanceSummary,
        progress: {
          progressPercentage: progress.progressPercentage,
          daysCompleted: progress.daysCompleted,
          totalDays: progress.totalDays,
          daysRemaining: progress.daysRemaining,
          isCompleted: progress.isCompleted,
          isPending: progress.isPending,
          isInProgress: progress.isInProgress,
        },
        certificate: canAccessCertificate
          ? {
              certificateFile: intern.certificateFile || null,
              certificateNumber:
                intern.certificateNumber ||
                getCertificateSerialNumber(intern.internshipId, intern.endDate),
              certificateIssuedAt: intern.certificateIssuedAt || intern.endDate,
              isAutoGenerated: true,
            }
          : null,
        hasCertificateUploaded: canAccessCertificate,
        isTerminated: intern.status === "TERMINATED",
        isOnHold: intern.status === "ON_HOLD",
      },
    });
  } catch (error) {
    console.error("Public certification verify error:", error);
    return NextResponse.json(
      { error: "Verification service temporarily unavailable. Please try again." },
      { status: 500 }
    );
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const rawId = body.id || body.internshipId;

    if (!rawId || !rawId.trim()) {
      return NextResponse.json(
        { error: "Please enter an Internship ID." },
        { status: 400 }
      );
    }

    const normalizedId = normalizeInternshipId(rawId);

    if (!isValidInternshipId(normalizedId)) {
      return NextResponse.json(
        { error: "Please enter a valid Internship ID, for example XSW-INTERN-001." },
        { status: 400 }
      );
    }

    const [intern] = await db
      .select()
      .from(interns)
      .where(and(eq(interns.internshipId, normalizedId), eq(interns.isPublished, true)));

    if (!intern) {
      return NextResponse.json(
        { error: "Internship record not found. Please check your Internship ID and try again." },
        { status: 404 }
      );
    }

    const progress = calculateInternshipProgress(intern.startDate, intern.endDate, intern.status);
    const canAccessCertificate = progress.isCompleted && intern.status !== "TERMINATED";

    return NextResponse.json({
      success: true,
      intern: {
        internshipId: intern.internshipId,
        fullName: intern.fullName,
        profileImage: intern.profileImage,
        role: intern.role,
        department: intern.department,
        internshipType: intern.internshipType,
        startDate: intern.startDate,
        endDate: intern.endDate,
        duration: intern.duration,
        status: intern.status,
        skills: intern.skills || [],
        description: intern.description,
        performanceSummary: intern.performanceSummary,
        progress: {
          progressPercentage: progress.progressPercentage,
          daysCompleted: progress.daysCompleted,
          totalDays: progress.totalDays,
          daysRemaining: progress.daysRemaining,
          isCompleted: progress.isCompleted,
          isPending: progress.isPending,
          isInProgress: progress.isInProgress,
        },
        certificate: canAccessCertificate
          ? {
              certificateFile: intern.certificateFile || null,
              certificateNumber:
                intern.certificateNumber ||
                getCertificateSerialNumber(intern.internshipId, intern.endDate),
              certificateIssuedAt: intern.certificateIssuedAt || intern.endDate,
              isAutoGenerated: true,
            }
          : null,
        hasCertificateUploaded: canAccessCertificate,
        isTerminated: intern.status === "TERMINATED",
        isOnHold: intern.status === "ON_HOLD",
      },
    });
  } catch (error) {
    console.error("Public certification verify error:", error);
    return NextResponse.json(
      { error: "Verification service temporarily unavailable. Please try again." },
      { status: 500 }
    );
  }
}
